/* Little Rest: all content lives locally; nothing is sent anywhere. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const pages=$$('.page');
function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));$$('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===id));location.hash=id;scrollTo(0,0);$('#nav').classList.remove('show')}
$$('[data-page]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.page)));$('#menuBtn').onclick=()=>$('#nav').classList.toggle('show');
const needs={Peace:['Relax your shoulders and take five slow breaths.','“Peace I leave with you; my peace I give you.” — John 14:27','Breathe With Me','breathe'],Rest:['Put your phone down for two minutes.','“Come to me, all you who are weary and burdened, and I will give you rest.” — Matthew 11:28','Five-minute reset','reset'],Faith:['Say one honest sentence to God.','“Be still, and know that I am God.” — Psalm 46:10','Faith & Peace','faith'],Quiet:['Look outside and notice three soft things.','“In quietness and trust is your strength.” — Isaiah 30:15','Thought Cloud','thought'],Encouragement:['Write down one thing you did well today.','“Do not fear, for I am with you.” — Isaiah 41:10','A little note for you','faith'],Hope:['Drink a glass of water, slowly.','“May the God of hope fill you with all joy and peace.” — Romans 15:13','My Little Reset Wheel','wheel']};
$('#needChoices').innerHTML=Object.keys(needs).map((n,i)=>`<button data-need="${n}">${['🤍','🌷','🙏','☁️','💗','✨'][i]} ${n}</button>`).join('');
$$('[data-need]').forEach(b=>b.onclick=()=>{const [action,verse,activity,target]=needs[b.dataset.need];$$('[data-need]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#checkResult').classList.remove('hidden');$('#checkResult').innerHTML=`<h3>For ${b.dataset.need.toLowerCase()}, try one tiny thing:</h3><p>🌸 <b>${action}</b></p><p class="verse">${verse}</p><p>Then you might like <b>${activity}</b>.</p><button class="primary" data-target="${target}">Start activity →</button>`; $('[data-target]').onclick=()=>target==='faith'||target==='reset'?go('faith'):target==='breathe'?openGame('breathe'):openModal(target)});
const small=['Drink some water.','Look outside for one minute.','Relax your jaw and shoulders.','Send yourself a kind thought.','Take five slow breaths.','Stand up and stretch.','Name one thing you are grateful for.'];$('#rightNow').onclick=()=>{let a=small[Math.floor(Math.random()*small.length)];$('#rightNowResult').innerHTML=`💧 <b>${a}</b><br><small>Just one small thing. That’s enough for this moment.</small><br><button class="text-btn" id="didIt">✓ I did it</button>`;$('#didIt').onclick=()=>$('#rightNowResult').innerHTML='🌸 Nice. One small act of care.'};
const modal=$('#modal'),content=$('#modalContent');function openModal(name){modal.classList.remove('hidden');modal.dataset.name=name; modalViews[name]?.()}function closeModal(){modal.classList.add('hidden');content.innerHTML='';if(drawState)saveDrawing()}$('#closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));
let drawState;
const modalViews={
 favorite(){let val=store.get('book','');content.innerHTML=`<h2>📚 Favorite Book</h2><p>Click the book and add a title to its cover.</p><div class="big-book" id="shelfBook">${val||'Your favorite book'}</div><input id="bookInput" maxlength="60" placeholder="Type your favorite book…" value="${val}"><button class="primary" id="bookSave">Save on my shelf</button>`;$('#shelfBook').onclick=()=>$('#bookInput').focus();$('#bookSave').onclick=()=>{let v=$('#bookInput').value.trim();store.set('book',v);$('#shelfBook').textContent=v||'Your favorite book'}},
 thought(){let val=store.get('thought','');content.innerHTML=`<h2>💭 Thought Cloud</h2><p>Click into the cloud and let what’s on your mind float out.</p><div class="cloud-input"><textarea id="thoughtText" rows="5" placeholder="What's on your mind?">${val}</textarea></div><button class="primary" id="thoughtSave">Save thought</button><button class="secondary" id="thoughtClear">Clear</button>`;$('#thoughtSave').onclick=()=>store.set('thought',$('#thoughtText').value);$('#thoughtClear').onclick=()=>{$('#thoughtText').value='';store.set('thought','')}},
 gratitude(){let notes=store.get('gratitude',[]);content.innerHTML=`<h2>🫙 Gratitude Jar</h2><p>Something I’m thankful for…</p><div class="jar" id="jar"></div><div class="button-row"><input id="gratitudeInput" maxlength="80" placeholder="A small good thing…"><button class="primary" id="addGratitude">Add note</button></div>`;const render=()=>{$('#jar').innerHTML=notes.map((n,i)=>`<span class="note" style="left:${12+(i*47)%130}px;bottom:${8+(i*27)%170}px;transform:rotate(${(i%3-1)*8}deg)">${n}</span>`).join('')};render();$('#addGratitude').onclick=()=>{let n=$('#gratitudeInput').value.trim();if(n){notes.push(n);store.set('gratitude',notes);$('#gratitudeInput').value='';render()}}},
 draw(){content.innerHTML=`<h2>✏️ Draw Your Reset</h2><p>Draw something that makes you feel peaceful.</p><div class="canvas-wrap"><canvas class="draw-canvas" id="drawCanvas"></canvas></div><div class="button-row"><button class="secondary tool active" data-tool="pencil">✏️ Pencil</button><button class="secondary tool" data-tool="eraser">🧹 Eraser</button><button class="secondary" id="undo">↩ Undo</button><button class="secondary" id="redo">↪ Redo</button><button class="secondary" id="clearDraw">🗑 Clear</button><button class="primary" id="saveDraw">💾 Save</button></div>`;initDraw()},
 comfort(){let selected=store.get('comfort',[]),items=[['💧','Water'],['📖','Book'],['🎧','Headphones'],['🌱','Plant'],['🧸','Blanket'],['🌸','Flower'],['🙏','Bible'],['☕','Drink']];content.innerHTML=`<h2>🌱 Things That Help Me</h2><p>Tap the things that help you feel calm.</p><div class="comfort-scene">${items.map(([e,n])=>`<button class="comfort-item ${selected.includes(n)?'selected':''}" data-item="${n}">${e}<small>${n}</small></button>`).join('')}</div><h3>My Little Comfort List</h3><p id="comfortList">${selected.length?selected.join(' · '):'Choose a few gentle helpers.'}</p>`;$$('[data-item]').forEach(b=>b.onclick=()=>{let n=b.dataset.item;selected=selected.includes(n)?selected.filter(x=>x!==n):[...selected,n];store.set('comfort',selected);b.classList.toggle('selected');$('#comfortList').textContent=selected.join(' · ')||'Choose a few gentle helpers.'})},
 places(){let places=store.get('places',[]);content.innerHTML=`<h2>🗺️ Peaceful Places</h2><p>Tap a place on the little map, then give it a name.</p><div class="map" id="map"></div><div class="button-row"><input id="placeName" placeholder="Name this peaceful place…"><button class="primary" id="savePlace">Save pin</button></div><p id="placeList"></p>`;let pending=null;const render=()=>{$('#map').innerHTML=places.map(p=>`<span class="marker" style="left:${p.x}%;top:${p.y}%" title="${p.n}">📍</span>`).join('');$('#placeList').textContent=places.map(p=>'📍 '+p.n).join('  ')||'No places pinned yet.'};render();$('#map').onclick=e=>{let r=e.currentTarget.getBoundingClientRect();pending={x:Math.round((e.clientX-r.left)/r.width*100),y:Math.round((e.clientY-r.top)/r.height*100)};$('#placeName').focus()};$('#savePlace').onclick=()=>{let n=$('#placeName').value.trim();if(n&&pending){places.push({...pending,n});store.set('places',places);$('#placeName').value='';pending=null;render()}}},
 step(){let done=store.get('steps',0),steps=['START','💧 Drink Water','🌬 Breathe','🧘 Pause','🙏 Pray / Reflect','🌱 Continue'];content.innerHTML=`<h2>👣 Today’s Small Step</h2><p>Press each stepping stone when you’re ready.</p><div class="path">${steps.map((s,i)=>`<button class="path-step ${i<=done?'done':''}" data-step="${i}">${i===done?'🦋 ':''}${s}</button>`).join('<div>↓</div>')}</div><p id="stepMessage"></p>`;$$('[data-step]').forEach(b=>b.onclick=()=>{let i=+b.dataset.step;if(i===done){done=Math.min(done+1,steps.length-1);store.set('steps',done);modalViews.step();if(done===steps.length-1)$('#stepMessage').textContent='You’re continuing gently. That counts. 🌸'}})},
 wheel(){let choices=store.get('wheel',[]),angle=0,spinning=false;content.innerHTML=`<h2>🎡 My Little Reset Wheel</h2><p>What would make your next little moment better?</p><div class="wheel-layout"><div class="wheel-wrap"><div class="pointer" aria-hidden="true">▼</div><div class="wheel" id="wheel" aria-label="Your reset wheel"></div></div><div><div class="button-row"><input id="wheelInput" maxlength="70" placeholder="Type your choice here…"><button class="primary" id="addChoice">+ Add</button></div><h3>My choices</h3><div class="choices-list" id="choicesList"></div><button class="secondary" id="clearChoices">Clear all choices</button><br><button class="primary" id="spinWheel">🎡 SPIN</button><div id="wheelResult" aria-live="polite"></div></div></div>`;
 const colors=['#f6b5c9','#e5cef6','#ffd2ad','#cce9d0','#f8e7a5','#bfe2ef','#f6c5a4','#d6d1f4','#f3bbd3','#cfebdf'];function render(){let w=$('#wheel'),list=$('#choicesList'),n=choices.length;let gradient=n?`conic-gradient(${choices.map((_,i)=>`${colors[i%colors.length]} ${i*360/n}deg ${(i+1)*360/n}deg`).join(',')})`:'#f1e8eb';w.style.background=gradient;let radius=Math.max(46,w.clientWidth*.31);w.innerHTML=choices.map((c,i)=>{let a=i*360/n+180/n;return `<span class="wheel-label" style="transform:rotate(${a}deg) translateY(-${radius}px) rotate(${-a}deg)">${c}</span>`}).join('');list.innerHTML=choices.map((c,i)=>`<div>✓ ${c}<button aria-label="Remove ${c}" data-remove="${i}">×</button></div>`).join('')||'<small>Add at least two choices to begin.</small>';$$('[data-remove]').forEach(b=>b.onclick=()=>{choices.splice(+b.dataset.remove,1);store.set('wheel',choices);render()})}render();$('#addChoice').onclick=()=>{let x=$('#wheelInput').value.trim();if(x){choices.push(x);store.set('wheel',choices);$('#wheelInput').value='';render()}};$('#wheelInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#addChoice').click()});$('#clearChoices').onclick=()=>{choices=[];store.set('wheel',choices);render()};$('#spinWheel').onclick=()=>{if(spinning||choices.length<2){$('#wheelResult').textContent='Add at least two little choices first. 🤍';return}spinning=true;let n=choices.length,win=Math.floor(Math.random()*n);/* The top pointer is at 270°, so the wheel's final angle must place the chosen slice centre there. */let center=win*360/n+180/n;let desired=270-center+(Math.random()*Math.min(8,120/n)-Math.min(4,60/n)),current=((angle%360)+360)%360;let delta=((desired-current+360)%360)+360*6;angle+=delta;let wheel=$('#wheel'),spin=$('#spinWheel');spin.disabled=true;spin.textContent='Spinning…';wheel.style.transform=`rotate(${angle}deg)`;setTimeout(()=>{let normalized=((angle%360)+360)%360;let underPointer=((270-normalized)%360+360)%360;let actual=Math.floor(underPointer/(360/n))%n;$('#wheelResult').innerHTML=`<h3>🌸 Your Little Pick</h3><p><b>“${choices[actual]}”</b></p><small>Maybe this can be your little thing for today. 🤍</small><br><button class="secondary" id="spinAgain">🎡 Spin again</button>`;$('#spinAgain').onclick=()=>$('#spinWheel').click();spin.disabled=false;spin.textContent='🎡 SPIN';spinning=false},5100)}
 }};
/* SVG is used for the wheel itself so every browser draws visible slices and labels. */
modalViews.wheel=function(){
 let choices=store.get('wheel',[]),angle=0,spinning=false;
 content.innerHTML=`<h2>🎡 My Little Reset Wheel</h2><p>What would make your next little moment better?</p><div class="wheel-layout"><div class="wheel-wrap"><div class="pointer" aria-hidden="true">▼</div><div class="wheel wheel-svg-host" id="wheel" aria-label="Your reset wheel"></div></div><div><div class="button-row"><input id="wheelInput" maxlength="70" placeholder="Type your choice here…"><button class="primary" id="addChoice">+ Add</button></div><h3>My choices</h3><div class="choices-list" id="choicesList"></div><button class="secondary" id="clearChoices">Clear all choices</button><br><button class="primary" id="spinWheel">🎡 SPIN</button><div id="wheelResult" aria-live="polite"></div></div></div>`;
 const colors=['#f6b5c9','#e5cef6','#ffd2ad','#cce9d0','#f8e7a5','#bfe2ef','#f6c5a4','#d6d1f4','#f3bbd3','#cfebdf'];
 const point=(degrees,r=48)=>{let radians=degrees*Math.PI/180;return [50+Math.cos(radians)*r,50+Math.sin(radians)*r]};
 const slice=(index,count)=>{let start=index*360/count,end=(index+1)*360/count,a=point(start),b=point(end),large=end-start>180?1:0;return `M 50 50 L ${a[0]} ${a[1]} A 48 48 0 ${large} 1 ${b[0]} ${b[1]} Z`};
 function render(){let wheel=$('#wheel'),list=$('#choicesList'),count=choices.length;
  wheel.innerHTML=count?`<svg class="wheel-svg" viewBox="0 0 100 100" role="img" aria-label="Wheel with ${count} choices">${choices.map((choice,index)=>{let middle=index*360/count+180/count,pos=point(middle,29),label=escapeHTML(choice.length>16?choice.slice(0,15)+'…':choice);return `<path d="${slice(index,count)}" fill="${colors[index%colors.length]}"/><text x="${pos[0]}" y="${pos[1]}" dominant-baseline="middle" text-anchor="middle">${label}</text>`}).join('')}<circle cx="50" cy="50" r="4" fill="#fff8fa" stroke="#d95d7b" stroke-width="1.5"/></svg>`:'<div class="wheel-empty">Add two choices<br>to make your wheel.</div>';
  list.innerHTML=choices.map((choice,index)=>`<div><span>✓ ${escapeHTML(choice)}</span><span><button class="choice-edit" aria-label="Edit ${escapeHTML(choice)}" data-edit="${index}">Edit</button><button aria-label="Remove ${escapeHTML(choice)}" data-remove="${index}">×</button></span></div>`).join('')||'<small>Add at least two choices to begin.</small>';
  $$('[data-remove]').forEach(button=>button.onclick=()=>{choices.splice(+button.dataset.remove,1);store.set('wheel',choices);render()});
  $$('[data-edit]').forEach(button=>button.onclick=()=>{let index=+button.dataset.edit,row=button.closest('div');row.innerHTML=`<input aria-label="Edit choice" maxlength="70" value="${escapeHTML(choices[index])}"><button class="primary choice-save">Save</button>`;let input=row.querySelector('input'),save=row.querySelector('.choice-save');input.focus();let commit=()=>{let value=input.value.trim();if(value){choices[index]=value;store.set('wheel',choices);render()}};save.onclick=commit;input.onkeydown=event=>{if(event.key==='Enter')commit()}});
 }
 render();
 $('#addChoice').onclick=()=>{let value=$('#wheelInput').value.trim();if(value){choices.push(value);store.set('wheel',choices);$('#wheelInput').value='';render()}};
 $('#wheelInput').addEventListener('keydown',event=>{if(event.key==='Enter')$('#addChoice').click()});
 $('#clearChoices').onclick=()=>{choices=[];store.set('wheel',choices);render()};
 $('#spinWheel').onclick=()=>{if(spinning||choices.length<2){$('#wheelResult').textContent='Add at least two little choices first. 🤍';return}spinning=true;let count=choices.length,winner=Math.floor(Math.random()*count),center=winner*360/count+180/count,desired=270-center+(Math.random()*Math.min(8,120/count)-Math.min(4,60/count)),current=((angle%360)+360)%360,delta=((desired-current+360)%360)+360*6;angle+=delta;let wheel=$('#wheel'),spin=$('#spinWheel');spin.disabled=true;spin.textContent='Spinning…';wheel.style.transform=`rotate(${angle}deg)`;setTimeout(()=>{let normalized=((angle%360)+360)%360,underPointer=((270-normalized)%360+360)%360,actual=Math.floor(underPointer/(360/count))%count;$('#wheelResult').innerHTML=`<h3>🌸 Your Little Pick</h3><p><b>“${escapeHTML(choices[actual])}”</b></p><small>Maybe this can be your little thing for today. 🤍</small><br><button class="secondary" id="spinAgain">🎡 Spin again</button>`;$('#spinAgain').onclick=()=>spin.click();spin.disabled=false;spin.textContent='🎡 SPIN';spinning=false},5100)};
};
function initDraw(){let c=$('#drawCanvas'),ctx=c.getContext('2d'),undo=[],redo=[],tool='pencil',drawing=false,last;function resize(){let old=c.toDataURL(),r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);if(old){let im=new Image();im.onload=()=>ctx.drawImage(im,0,0,r.width,r.height);im.src=old}}resize();let saved=store.get('drawing',null);if(saved){let im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.clientWidth,c.clientHeight);im.src=saved}function snap(){undo.push(c.toDataURL());if(undo.length>20)undo.shift();redo=[]}function pos(e){let r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function start(e){e.preventDefault();snap();drawing=true;last=pos(e);c.setPointerCapture(e.pointerId)}function move(e){if(!drawing)return;let p=pos(e);ctx.lineWidth=tool==='eraser'?24:4;ctx.lineCap='round';ctx.strokeStyle=tool==='eraser'?'#fff':'#c76d94';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}function end(){drawing=false}c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);c.addEventListener('pointerup',end);$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});function load(data){let im=new Image();im.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.clientWidth,c.clientHeight)};im.src=data}$('#undo').onclick=()=>{if(undo.length){redo.push(c.toDataURL());load(undo.pop())}};$('#redo').onclick=()=>{if(redo.length){undo.push(c.toDataURL());load(redo.pop())}};$('#clearDraw').onclick=()=>{snap();ctx.clearRect(0,0,c.width,c.height)};$('#saveDraw').onclick=()=>saveDrawing();drawState={c};}
function saveDrawing(){if(drawState)store.set('drawing',drawState.c.toDataURL());}
const games=[['🌬 Calm',[['breathe','Breathe With Me'],['follow','Follow the Circle']]],['🌱 Create',[['garden','Grow a Garden'],['heart','Heart Garden'],['rainbow','Build a Rainbow']]],['🧩 Play',[['memory','Memory Match'],['sort','Sort the Colors'],['stars','Connect the Stars']]],['🌊 Unwind',[['waves','Make Waves'],['feather','Feather Float'],['cloud','Drag the Cloud']]],['🎵 Create',[['melody','Calm Melody']]],['💗 Maybe Try This',[['diff','Find the Difference'],['strawberry','Strawberry Seeds'],['bottles','Fill the Bottles'],['fruit','Grow Your Fruit'],['trash','Leave It Behind'],['fire','Let It Go']]]];$('#gameGroups').innerHTML=games.map(([t,arr])=>`<article class="game-group"><h3>${t}</h3><div class="game-list">${arr.map(([id,n])=>`<button data-game="${id}">${n}</button>`).join('')}</div></article>`).join('');$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));
const reflections={breathe:'What changed, even a little, after you gave yourself a few slow breaths?',follow:'You do not have to be perfect to return to the present.',garden:'Little things grow with small, patient care — including you.',heart:'Notice one kind thing your heart could use today.',rainbow:'Different small pieces can make something lovely together.',memory:'Your mind can take its time. There is no rush here.',sort:'Making a little room for each feeling can bring calm.',stars:'You are finding your way one small point at a time.',waves:'Like a ripple, one gentle choice can soften a moment.',feather:'You are allowed to move lightly through this moment.',cloud:'Let one thought drift by without having to solve it.',melody:'Which note felt the softest to you?',diff:'Noticing small things gently trains your eyes to notice good ones too.',strawberry:'There is no wrong way to decorate something sweet.',bottles:'You get to choose how you fill your own little space.',fruit:'Growth is slow and quiet, and that is alright.',trash:'You do not have to carry everything with you.',fire:'It is okay to let this moment pass.'};
function openGame(name){modal.classList.remove('hidden');let t=$('#gameTemplate').content.cloneNode(true);content.innerHTML='';content.append(t);$('.game-head h2').textContent=({breathe:'🌬 Breathe With Me',follow:'🌀 Follow the Circle',garden:'🌱 Grow a Garden',heart:'💗 Heart Garden',rainbow:'🌈 Build a Rainbow',memory:'🧠 Memory Match',sort:'🎨 Sort the Colors',stars:'⭐ Connect the Stars',waves:'🌊 Make Waves',feather:'🪶 Feather Float',cloud:'☁️ Drag the Cloud',melody:'🎵 Make a Calm Melody',diff:'🔎 Find the Difference',strawberry:'🍓 Add Seeds to the Strawberries',bottles:'🧴 Fill the Bottles',fruit:'🍎 Grow Your Fruit',trash:'🗑️ Things I Want to Leave Behind',fire:'🔥 Let It Go'})[name];$('.close-game').onclick=closeModal;$('.play-again').onclick=()=>openGame(name);gameFns[name]($('.game-stage'));$('.game-stage').insertAdjacentHTML('afterend',`<aside class="game-reflection">💭 <b>A little connection</b><span>${reflections[name]}</span></aside>`)}
function drag(el,area,onDrop){let off=null,activePointer=null;function release(){if(activePointer!==null&&el.hasPointerCapture(activePointer))el.releasePointerCapture(activePointer);activePointer=null;off=null}el.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;let r=area.getBoundingClientRect(),box=el.getBoundingClientRect();e.preventDefault();e.stopPropagation();off={x:e.clientX-box.left,y:e.clientY-box.top};activePointer=e.pointerId;el.setPointerCapture(e.pointerId);el.classList.add('is-dragging')});el.addEventListener('pointermove',e=>{if(!off||e.pointerId!==activePointer)return;let r=area.getBoundingClientRect();el.style.left=Math.max(0,Math.min(r.width-el.offsetWidth,e.clientX-r.left-off.x))+'px';el.style.top=Math.max(0,Math.min(r.height-el.offsetHeight,e.clientY-r.top-off.y))+'px'});el.addEventListener('pointerup',e=>{if(e.pointerId!==activePointer)return;release();el.classList.remove('is-dragging');onDrop?.(el)});el.addEventListener('pointercancel',()=>{release();el.classList.remove('is-dragging')});el.addEventListener('lostpointercapture',()=>{off=null;activePointer=null;el.classList.remove('is-dragging')})}
const gameFns={
 breathe(stage){stage.innerHTML='<div class="breath-circle"><div id="breathWord">Ready?<b>🌸</b><small>Press Start</small></div></div><div><button class="primary" id="bStart">Start</button><button class="secondary" id="bPause">Pause</button><button class="secondary" id="bRestart">Restart</button></div>';let phases=[['Breathe In',4,1],['Hold',2,1],['Breathe Out',6,0]],p=0,left=4,timer,paused=false,cycles=0,circle=$('.breath-circle');function paint(){let [word,secs,scale]=phases[p];$('#breathWord').innerHTML=`${word}<b>${left}</b><small>${paused?'Paused':word}</small>`;circle.style.transform=`scale(${scale?1.3:1})`}function tick(){if(paused)return;paint();left--;if(left<0){p=(p+1)%3;left=phases[p][1];if(p===0&&++cycles===3){clearInterval(timer);$('#breathWord').innerHTML='🌸<b>Done</b><small>You gave yourself a moment to breathe.</small>';return}}}function start(){clearInterval(timer);p=0;left=4;cycles=0;paused=false;tick();timer=setInterval(tick,1000)}$('#bStart').onclick=start;$('#bPause').onclick=()=>{paused=!paused;$('#bPause').textContent=paused?'Resume':'Pause';paint()};$('#bRestart').onclick=start},
 follow(stage){stage.innerHTML='<p>Move your finger or mouse around the circle and follow the pink dot.</p><div class="follow-area"><i class="follow-dot"></i><i class="follow-user"></i></div>';let a=0,area=$('.follow-area'),dot=$('.follow-dot'),user=$('.follow-user'),raf;function frame(){a+=.018;let r=area.clientWidth/2-15,c=area.clientWidth/2;dot.style.left=c+Math.cos(a)*r+'px';dot.style.top=c+Math.sin(a)*r+'px';raf=requestAnimationFrame(frame)}frame();area.onpointermove=e=>{let r=area.getBoundingClientRect();user.style.left=e.clientX-r.left+'px';user.style.top=e.clientY-r.top+'px'}},
 garden(stage){stage.innerHTML='<p>Drag the helper into the glowing garden spot. Each step will unlock the next.</p><div class="drag-play garden-play"><div class="soil"></div><div class="garden-target"><span>Drop here</span></div><span class="plant">🪴</span><span class="draggable active-helper" data-kind="seed" style="left:24px;top:24px">🌰</span><span class="draggable" data-kind="water" style="left:24px;top:24px">💧</span><span class="draggable" data-kind="sun" style="left:24px;top:24px">☀️</span></div><p id="gardenMsg"><b>Step 1 of 3:</b> Put the seed in the soil.</p>';let area=$('.garden-play'),order=['seed','water','sun'],labels=['Put the seed in the soil.','Give your seed some water.','Let the sunlight reach your plant.'],step=0,target=$('.garden-target');function setActive(){let expected=order[step];$$('.draggable').forEach(el=>{let active=el.dataset.kind===expected;el.classList.toggle('active-helper',active);el.style.display=active?'grid':'none';if(active){el.style.left='24px';el.style.top='24px'}});target.classList.toggle('ready',step<3)}function intersects(el,zone){let a=el.getBoundingClientRect(),b=zone.getBoundingClientRect(),pad=18;return a.left<b.right+pad&&a.right>b.left-pad&&a.top<b.bottom+pad&&a.bottom>b.top-pad}$$('.draggable').forEach(el=>drag(el,area,el=>{if(el.dataset.kind!==order[step])return;if(intersects(el,target)){el.style.display='none';step++;let plant=$('.plant');plant.textContent=step===1?'🌱':step===2?'🌿':'🌸';if(step===3){target.classList.remove('ready');target.innerHTML='🌸';$('#gardenMsg').innerHTML='<b>Your little garden bloomed!</b> You gave it patient care, one small step at a time.'}else{$('#gardenMsg').innerHTML=`<b>Step ${step+1} of 3:</b> ${labels[step]}`;setActive()}}else{el.style.left='24px';el.style.top='24px';$('#gardenMsg').innerHTML=`<b>Almost!</b> Try dropping the ${el.dataset.kind} right on the glowing spot.`}}));setActive()},
 heart(stage){stage.innerHTML='<p>Draw small heart shapes; lift your finger to plant a flower.</p><canvas class="heart-canvas"></canvas><p id="heartMsg"></p>';let c=$('.heart-canvas'),r=c.getBoundingClientRect();c.width=r.width;c.height=r.height;let ctx=c.getContext('2d'),down=false,count=0;c.onpointerdown=e=>{down=true;ctx.beginPath();let q={x:e.offsetX,y:e.offsetY};ctx.moveTo(q.x,q.y)};c.onpointermove=e=>{if(down){ctx.lineTo(e.offsetX,e.offsetY);ctx.strokeStyle='#e777a0';ctx.lineWidth=4;ctx.stroke()}};c.onpointerup=e=>{if(down){down=false;count++;ctx.font='28px sans-serif';ctx.fillText('🌸',e.offsetX-12,e.offsetY+8);$('#heartMsg').textContent=`${count} flower${count>1?'s':''} in your heart garden.`}}},
 rainbow(stage){let colors=['🔴','🟠','🟡','🟢','🔵'];stage.innerHTML=`<p>Drag each color into the matching spot in rainbow order.</p><div class="rainbow-stage" id="rainbowStage"><div class="slots">${colors.map((x,i)=>`<div class="rain-slot" data-slot="${i}"></div>`).join('')}</div><div class="slots rain-pieces" id="rainPieces">${[...colors].sort(()=>Math.random()-.5).map((x,i)=>`<span class="rain-piece" data-color="${colors.indexOf(x)}">${x}</span>`).join('')}</div></div><p id="rainMsg"></p>`;let area=$('#rainbowStage'),done=0,areaRect=area.getBoundingClientRect();area.style.position='relative';area.style.width=areaRect.width+'px';area.style.height=areaRect.height+'px';let pieceRects=$$('.rain-piece').map(el=>el.getBoundingClientRect());$$('.rain-piece').forEach((el,i)=>{let r=pieceRects[i];el.style.position='absolute';el.style.left=(r.left-areaRect.left)+'px';el.style.top=(r.top-areaRect.top)+'px';el.style.margin='0'});$$('.rain-piece').forEach(el=>drag(el,area,el=>{let slot=$(`[data-slot="${el.dataset.color}"]`),a=el.getBoundingClientRect(),b=slot.getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top){slot.textContent=el.textContent;el.remove();if(++done===5)$('#rainMsg').textContent='🌈 You built a rainbow!'}}))},
 memory(stage){let vals=['🌸','🌸','☁️','☁️','🦋','🦋','⭐','⭐'].sort(()=>Math.random()-.5),open=[],matched=0;stage.innerHTML=`<div class="memory">${vals.map((v,i)=>`<button data-v="${v}" data-i="${i}">?</button>`).join('')}</div><p id="memMsg"></p>`;$$('.memory button').forEach(b=>b.onclick=()=>{if(b.classList.contains('open')||open.length===2)return;b.textContent=b.dataset.v;b.classList.add('open');open.push(b);if(open.length===2){if(open[0].dataset.v===open[1].dataset.v){matched+=2;open=[];if(matched===8)$('#memMsg').textContent='🌸 Every little pair found its way home.'}else setTimeout(()=>{open.forEach(x=>{x.textContent='?';x.classList.remove('open')});open=[]},650)}})},
 sort(stage){let data=[['🌸','pink'],['💜','lav'],['🍑','peach'],['🤍','cream']],done=0;stage.innerHTML=`<p>Gently sort each object into its matching color home.</p><div class="sort-area">${data.map(([,c])=>`<div class="sort-zone" data-zone="${c}" style="background:${c==='pink'?'#f7c9d6':c==='lav'?'#e6d9f5':c==='peach'?'#ffe0cc':'#fff9e9'}">${c}</div>`).join('')}</div><div class="sort-area">${data.sort(()=>Math.random()-.5).map(([x,c])=>`<span class="sort-item" data-color="${c}" style="position:relative">${x}</span>`).join('')}</div><p id="sortMsg"></p>`;$$('.sort-item').forEach(el=>drag(el,stage,el=>{let z=$(`[data-zone="${el.dataset.color}"]`),a=el.getBoundingClientRect(),b=z.getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top){z.append(el);el.style.position='static';if(++done===4)$('#sortMsg').textContent='Everything found its soft little place.'}}))},
 stars(stage){let pts=[[12,70],[30,25],[52,52],[72,15],[88,72]],next=0;stage.innerHTML=`<p>Connect the stars in order: 1 → 5.</p><div class="stars"><svg class="star-svg" id="starSvg"></svg>${pts.map((p,i)=>`<button class="star" data-i="${i}" style="left:${p[0]}%;top:${p[1]}%">${i+1}⭐</button>`).join('')}</div><p id="starMsg"></p>`;$$('.star').forEach(b=>b.onclick=()=>{if(+b.dataset.i!==next)return;b.classList.add('active');if(next){let a=pts[next-1],z=pts[next],svg=$('#starSvg');svg.innerHTML+=`<line x1="${a[0]}%" y1="${a[1]}%" x2="${z[0]}%" y2="${z[1]}%" stroke="#d587a0" stroke-width="4"/>`}if(++next===5)$('#starMsg').textContent='✨ A sweet little constellation appeared.'})},
 waves(stage){stage.innerHTML='<p>Touch the water and make as many quiet ripples as you like.</p><div class="water"></div>';let w=$('.water');w.onpointerdown=e=>{let r=w.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,s=document.createElement('i');s.className='ripple';s.style.left=x+'px';s.style.top=y+'px';s.style.width=s.style.height='5px';w.append(s);setTimeout(()=>s.remove(),1500)}},
 feather(stage){stage.innerHTML='<p>Move your finger or mouse to make a little wind.</p><div class="feather-area"><span class="feather" style="left:45%;top:42%">🪶</span></div>';let a=$('.feather-area'),f=$('.feather');a.onpointermove=e=>{let r=a.getBoundingClientRect();f.style.left=Math.max(0,Math.min(r.width-45,e.clientX-r.left-20))+'px';f.style.top=Math.max(0,Math.min(r.height-45,e.clientY-r.top-20))+'px'}},
 cloud(stage){stage.innerHTML='<p>Drag the cloud across the sky. It leaves little stars behind.</p><div class="cloud-area"><span class="drag-cloud" style="left:30%;top:30%">☁️</span></div>';let a=$('.cloud-area'),c=$('.drag-cloud');drag(c,a,()=>{let s=document.createElement('span');s.textContent='✦';s.style.cssText=`position:absolute;left:${c.offsetLeft+20}px;top:${c.offsetTop+55}px;color:white`;a.append(s)})},
 melody(stage){let notes=[261.6,293.7,329.6,392,440,493.9],seq=[];stage.innerHTML=`<p>Tap a few gentle notes, then play your tiny melody.</p><div class="melody">${notes.map((n,i)=>`<button data-note="${n}">${['C','D','E','G','A','B'][i]}</button>`).join('')}</div><p id="melodySeq">No notes yet</p><button class="primary" id="playMelody">Play my melody</button><button class="secondary" id="undoMelody">Undo</button><button class="secondary" id="clearMelody">Clear</button>`;function tone(f,t=0){let ac=new (window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.12,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.45);o.connect(g).connect(ac.destination);o.start(t);o.stop(t+.5)}function render(){$('#melodySeq').textContent=seq.length?seq.map(n=>notes.indexOf(n)+1).join(' · '):'No notes yet'}$$('[data-note]').forEach(b=>b.onclick=()=>{let n=+b.dataset.note;seq.push(n);tone(n);render()});$('#undoMelody').onclick=()=>{seq.pop();render()};$('#clearMelody').onclick=()=>{seq=[];render()};$('#playMelody').onclick=()=>seq.forEach((n,i)=>tone(n,i*.42))},
 diff(stage){let base=[{e:'🌼',x:14,y:66},{e:'⭐',x:70,y:14},{e:'🦋',x:46,y:36},{e:'🍄',x:80,y:72},{e:'🌸',x:24,y:20},{e:'☁️',x:58,y:52},{e:'🌿',x:8,y:32},{e:'🌷',x:52,y:78}],diffs=[0,2,4],altE={0:null,2:'🌻',4:'🍒'},found=new Set();function scene(id,useAlt){return `<div class="diff-scene" id="${id}">${base.map((it,i)=>{let e=it.e;if(useAlt&&diffs.includes(i)){if(altE[i]===null)return '';e=altE[i]}return `<span class="diff-item" style="left:${it.x}%;top:${it.y}%">${e}</span>`}).join('')}${diffs.map(i=>`<button class="diff-spot" data-i="${i}" style="left:${base[i].x-3}%;top:${base[i].y-3}%" aria-label="Find the difference"></button>`).join('')}</div>`}stage.innerHTML=`<p>Can you find 3 little differences? 🔎</p><div class="diff-wrap">${scene('sceneA',false)}${scene('sceneB',true)}</div><p id="diffMsg">0 / 3 found 💗</p>`;$$('.diff-spot').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;if(found.has(i))return;found.add(i);$$(`.diff-spot[data-i="${i}"]`).forEach(x=>x.classList.add('found'));$('#diffMsg').textContent=found.size<3?`${found.size} / 3 found 💗`:'You found them all! 🌸'})},
 strawberry(stage){stage.innerHTML='<p>Add some little seeds to the strawberries 🍓 — there is no wrong way.</p><div class="berry-scene" id="berryScene"><span class="berry">🍓</span><span class="berry">🍓</span></div><div class="seed-tray">'+Array(6).fill('<span class="seed">🟡</span>').join('')+'</div><p><small>Tap a seed, then tap anywhere on a strawberry.</small></p>';let scene=$('#berryScene'),activeSeed=null;$$('.seed').forEach(s=>s.onclick=()=>{$$('.seed').forEach(x=>x.classList.remove('selected'));s.classList.add('selected');activeSeed=s});scene.onclick=e=>{if(!activeSeed||!e.target.classList.contains('berry'))return;let r=e.target.getBoundingClientRect(),seed=document.createElement('span');seed.className='placed-seed';seed.textContent='•';seed.style.left=(e.clientX-r.left)+'px';seed.style.top=(e.clientY-r.top)+'px';e.target.append(seed)}},
 bottles(stage){let colors=[['🩷','#f7b8cd'],['💙','#a9d4f5'],['💛','#f7e08a'],['💚','#b9e3b0'],['💜','#d9c6f2']];stage.innerHTML=`<p>Fill the bottles however you like 🧴</p><div class="bottle-scene">${[0,1,2].map(i=>`<div class="bottle" data-b="${i}"><div class="fill" style="height:0%"></div></div>`).join('')}</div><div class="bottle-colors">${colors.map((c,i)=>`<button data-c="${i}" style="background:${c[1]}" aria-label="${c[0]}"></button>`).join('')}</div><p><small>Tap a color, then tap a bottle to add to it.</small></p>`;let activeColor=0;$$('.bottle-colors button').forEach(b=>b.onclick=()=>{$$('.bottle-colors button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeColor=+b.dataset.c});$$('.bottle-colors button')[0].classList.add('selected');$$('.bottle').forEach(b=>b.onclick=()=>{let fill=b.querySelector('.fill'),h=Math.min(100,parseFloat(fill.style.height)+20);fill.style.height=h+'%';fill.style.background=colors[activeColor][1]})},
 fruit(stage){let fruits=[['🍎','Love'],['🍊','Joy'],['🍋','Peace'],['🍇','Patience'],['🍓','Kindness'],['🍑','Goodness'],['🌱','Faithfulness'],['🥝','Gentleness'],['🍐','Self-control']],grown=store.get('fruitTree',[]);function render(){stage.innerHTML=`<p>What fruit would you like to grow today? 🌳</p><div class="fruit-tree">${grown.length?grown.map(f=>`<span class="grown-fruit">${f}</span>`).join(''):'<small>Your tree is just starting out.</small>'}</div><div class="fruit-choices">${fruits.map(([e,n])=>`<button data-f="${e}">${e} ${n}</button>`).join('')}</div><button class="text-btn" id="fruitClear">🍂 Clear my tree</button>`;$$('.fruit-choices button').forEach(b=>b.onclick=()=>{grown.push(b.dataset.f);store.set('fruitTree',grown);render()});$('#fruitClear').onclick=()=>{grown=[];store.set('fruitTree',grown);render()}}render()},
 trash(stage){let count=store.get('trashCount',0);stage.innerHTML=`<p>Type something you want to let go of, then put it in the bag.</p><div class="bag-scene"><span class="bag-icon" id="bagIcon">🗑️</span><p class="bag-fill-count" id="bagCount">${count} let go so far</p></div><div class="tryit-addrow"><input id="trashInput" maxlength="60" placeholder="Overthinking, a bad day, stress…"><button class="primary" id="trashAdd">Put it in the bag 🗑️</button></div><p id="trashMsg"></p>`;$('#trashAdd').onclick=()=>{let v=$('#trashInput').value.trim();if(!v)return;let icon=$('#bagIcon');icon.classList.remove('wobble');void icon.offsetWidth;icon.classList.add('wobble');count++;store.set('trashCount',count);$('#bagCount').textContent=`${count} let go so far`;$('#trashInput').value='';$('#trashMsg').textContent="You don't have to carry everything with you. 💗"}},
 fire(stage){stage.innerHTML='<p>Type something you want to leave behind, then let it go.</p><div class="tryit-addrow"><input id="fireInput" maxlength="60" placeholder="Today was stressful…"><button class="primary" id="fireAdd">Let it go 🔥</button></div><div class="fire-scene" id="fireScene"><span class="fire-flame">🔥</span></div><p id="fireMsg"></p>';$('#fireAdd').onclick=()=>{let v=$('#fireInput').value.trim();if(!v)return;let scene=$('#fireScene'),note=document.createElement('span');note.className='fire-note';note.textContent=v;note.style.left='16px';note.style.bottom='86px';scene.append(note);$('#fireInput').value='';setTimeout(()=>{note.classList.add('fire-burning');setTimeout(()=>{note.remove();$('#fireMsg').textContent="It's okay to let this moment pass. 💗"},550)},450)}}
 };
const verses=['“Come to me, all you who are weary and burdened, and I will give you rest.” — Matthew 11:28','“Be still, and know that I am God.” — Psalm 46:10','“Cast all your anxiety on him because he cares for you.” — 1 Peter 5:7','“The Lord is my shepherd; I lack nothing.” — Psalm 23:1','“Trust in the Lord with all your heart.” — Proverbs 3:5','“God is our refuge and strength, an ever-present help in trouble.” — Psalm 46:1','“My peace I give you.” — John 14:27','“Those who hope in the Lord will renew their strength.” — Isaiah 40:31'];let currentVerse=verses[0];function showVerse(){$('#verseText').textContent=currentVerse}showVerse();$('#newVerse').onclick=()=>{currentVerse=verses[Math.floor(Math.random()*verses.length)];showVerse()};$('#saveVerse').onclick=()=>{let a=store.get('verses',[]);if(!a.includes(currentVerse))a.push(currentVerse);store.set('verses',a);renderSaved()};function renderSaved(){$('#savedVerses').innerHTML=store.get('verses',[]).map(v=>`<p>🤍 ${v}</p>`).join('')}renderSaved();
const prayers={Stress:'God, meet me in this busy feeling. Help me take this moment one breath at a time. Amen.',School:'God, give me a clear mind and a gentle heart as I learn today. Amen.',Fear:'God, stay close when I feel afraid. Remind me I do not carry this alone. Amen.',Uncertainty:'God, hold what I cannot figure out. Help me trust your next small step. Amen.',Gratitude:'Thank you, God, for the quiet good things around me today. Amen.',Strength:'God, lend me your strength for just this moment. Amen.',Rest:'God, let my mind and body rest in your care. Amen.',Hope:'God, plant a small bright hope in me today. Amen.'};let type='Stress';$('#prayerTypes').innerHTML=Object.keys(prayers).map(x=>`<button data-prayer="${x}">${x}</button>`).join('');function showPrayer(){$('#prayerText').textContent=prayers[type]}showPrayer();$$('[data-prayer]').forEach(b=>b.onclick=()=>{type=b.dataset.prayer;showPrayer()});$('#newPrayer').onclick=()=>{type=Object.keys(prayers)[Math.floor(Math.random()*8)];showPrayer()};
const notes=['You are allowed to take up soft space.','Small progress is still a kind of progress.','You do not have to earn rest.','A slow day can still be a meaningful day.','You can begin again, gently.','There is no rush in becoming.','You are doing more than you think.','This feeling is a visitor, not your whole story.','Take the next kind step, not every step.','Your heart deserves patience too.','You are safe to pause.','One breath can be a fresh beginning.','You are not behind in your own life.','Let today be little if it needs to be.','Quiet moments count.','You are held, even in the messy parts.','Be as kind to yourself as you are to others.','The sun will find you again.','You can put down what is too heavy for today.','You matter without performing.','Your softness is not a weakness.','You have made it through every hard day so far.','You are allowed to change your mind.','Tiny joys are real joys.','Your pace is enough.','You can make room for hope.','Being here is enough for now.','There is grace for this moment.','You are allowed a fresh page.','Take good care of your tender heart.'];let note=0;function showNote(){$('#noteText').textContent=notes[note]}showNote();$('#newNote').onclick=()=>{note=(note+1)%notes.length;showNote()};
let resetSeconds=300,resetTimer=null;function renderReset(){let m=Math.floor(resetSeconds/60),s=resetSeconds%60,minute=Math.min(5,5-Math.floor((300-resetSeconds)/60));$('#resetClock').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#resetText').textContent=resetSeconds===0?'You gave yourself five minutes. That matters. 🤍':['Breathe.','Relax your shoulders.','Look around you.','Think of one thing you’re grateful for.','Pray or sit quietly.'][Math.max(0,minute-1)]}function startReset(){clearInterval(resetTimer);resetTimer=setInterval(()=>{if(resetSeconds>0){resetSeconds--;renderReset()}else clearInterval(resetTimer)},1000)}$('#resetStart').onclick=startReset;$('#resetPause').onclick=()=>clearInterval(resetTimer);$('#resetRestart').onclick=()=>{clearInterval(resetTimer);resetSeconds=300;renderReset()};renderReset();
$('#journalText').value=store.get('journal','');$('#saveJournal').onclick=()=>store.set('journal',$('#journalText').value);$('#clearJournal').onclick=()=>{$('#journalText').value='';store.set('journal','')};

/* ---------- 🌸 Maybe Try This? ---------- */
function flash(msg){let f=$('#tryitFlash');if(f){f.textContent=msg;setTimeout(()=>{if(f)f.textContent=''},1600)}}

/* Quick, optional mood/energy/time/location check-in. Auto-saved on every tap. */
const tryitMoods=[['😊','Happy'],['😌','Calm'],['😐','Okay'],['😔','Sad'],['😫','Stressed'],['😴','Tired'],['😩','Overwhelmed'],['😶','Bored']];
const tryitEnergy=['Low','Medium','High'];
const tryitTimes=['10 minutes','30 minutes','1 hour','Several hours'];
const tryitLocations=['Home','Outside','Anywhere'];
let checkin=store.get('checkin',{mood:'',energy:'',time:'',location:''});
function renderCheckinGroup(sel,arr,key,withEmoji){
  $(sel).innerHTML=arr.map(v=>{let label=withEmoji?v[1]:v,emoji=withEmoji?v[0]+' ':'';return `<button data-v="${label}" class="${checkin[key]===label?'selected':''}">${emoji}${label}</button>`}).join('');
  $$(sel+' button').forEach(b=>b.onclick=()=>{checkin[key]=checkin[key]===b.dataset.v?'':b.dataset.v;store.set('checkin',checkin);renderCheckinGroup(sel,arr,key,withEmoji)});
}
renderCheckinGroup('#moodChips',tryitMoods,'mood',true);
renderCheckinGroup('#energyChips',tryitEnergy,'energy',false);
renderCheckinGroup('#timeChips',tryitTimes,'time',false);
renderCheckinGroup('#locationChips',tryitLocations,'location',false);

/* One-question-at-a-time flow. Every answer auto-saves; no Save button needed. */
const tryitProfile=store.get('tryitProfile',{freeTime:[],food:[],place:[]});
let wantToTry=store.get('wantToTry',[]),happyList=store.get('happyList',[]),savedIdeas=store.get('savedIdeas',[]);
let recentSuggestions=store.get('recentSuggestions',[]),completedSuggestions=store.get('completedSuggestions',[]);
const tryitSteps=[
 {key:'freeTime',q:'What do you usually like doing when you have free time?',opts:['Watch movies','Listen to music','Play games','Go outside','Read','Draw','Sleep / rest','Hang out with friends']},
 {key:'food',q:'What food always makes you happy?',opts:['Ramen','Pizza','Fries','Ice cream','Coffee','Milk tea']},
 {key:'place',q:'Where do you like going when you want to relax?',opts:['Café','Mall','Park','Beach','Home','Baguio']},
 {key:'wantToTry',q:'What are some things you’ve always wanted to try?',list:true},
 {key:'happyList',q:'What are some little things that make you happy?',list:true}
];
let tryitStepIdx=Math.min(store.get('tryitStepIdx',0),tryitSteps.length-1);
function renderTryitStep(){
  let s=tryitSteps[tryitStepIdx],progress=`Question ${tryitStepIdx+1} of ${tryitSteps.length}`,body;
  if(s.list){
    let arr=s.key==='wantToTry'?wantToTry:happyList;
    body=`<div class="tryit-addrow"><input id="tryitListInput" maxlength="60" placeholder="Type one, then press Add…"><button class="primary" id="tryitListAdd">+ Add</button></div><div class="tryit-chips" id="tryitListChips">${arr.map((v,i)=>`<span>${escapeHTML(typeof v==='string'?v:v.item)}<button data-i="${i}" aria-label="Remove">×</button></span>`).join('')}</div>`;
  }else{
    let sel=tryitProfile[s.key]||(tryitProfile[s.key]=[]);
    body=`<div class="tryit-options">${s.opts.map(o=>`<button data-o="${escapeHTML(o)}" class="${sel.includes(o)?'selected':''}">${o}</button>`).join('')}<button data-o="__other">Something else…</button></div><div id="tryitOtherRow"></div>`;
  }
  $('#tryitFlow').innerHTML=`<div class="tryit-question"><p class="tryit-progress">${progress}</p><h3>${s.q}</h3>${body}<div class="saved-flash" id="tryitFlash"></div><div class="tryit-nav">${tryitStepIdx>0?'<button class="secondary" id="tryitBack">← Back</button>':''}<button class="text-btn" id="tryitSkip">Skip</button>${tryitStepIdx<tryitSteps.length-1?'<button class="primary" id="tryitNext">Continue →</button>':'<button class="primary" id="tryitDone">Done for now 🌸</button>'}</div></div>`;
  wireTryitStep(s);
}
function wireTryitStep(s){
  if(s.list){
    let arr=s.key==='wantToTry'?wantToTry:happyList;
    $('#tryitListAdd').onclick=()=>{let v=$('#tryitListInput').value.trim();if(!v)return;arr.push(s.key==='wantToTry'?{item:v,completed:false,created:Date.now()}:v);store.set(s.key,arr);$('#tryitListInput').value='';renderTryitStep();flash('Added to your little list 💗')};
    $('#tryitListInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#tryitListAdd').click()});
    $$('#tryitListChips button').forEach(b=>b.onclick=()=>{arr.splice(+b.dataset.i,1);store.set(s.key,arr);renderTryitStep()});
  }else{
    $$('.tryit-options button[data-o]').forEach(b=>b.onclick=()=>{
      if(b.dataset.o==='__other'){$('#tryitOtherRow').innerHTML='<div class="tryit-addrow"><input id="tryitOtherInput" maxlength="60" placeholder="Type your own…"><button class="primary" id="tryitOtherAdd">Add</button></div>';$('#tryitOtherAdd').onclick=()=>{let v=$('#tryitOtherInput').value.trim();if(!v)return;let sel=tryitProfile[s.key];if(!sel.includes(v))sel.push(v);store.set('tryitProfile',tryitProfile);renderTryitStep();flash('✓ Saved')};return}
      let sel=tryitProfile[s.key];if(sel.includes(b.dataset.o))tryitProfile[s.key]=sel.filter(x=>x!==b.dataset.o);else sel.push(b.dataset.o);store.set('tryitProfile',tryitProfile);renderTryitStep();flash('✓ Saved')
    });
  }
  $('#tryitSkip')&&($('#tryitSkip').onclick=()=>{tryitStepIdx=Math.min(tryitStepIdx+1,tryitSteps.length-1);store.set('tryitStepIdx',tryitStepIdx);renderTryitStep()});
  $('#tryitBack')&&($('#tryitBack').onclick=()=>{tryitStepIdx=Math.max(tryitStepIdx-1,0);store.set('tryitStepIdx',tryitStepIdx);renderTryitStep()});
  $('#tryitNext')&&($('#tryitNext').onclick=()=>{tryitStepIdx=Math.min(tryitStepIdx+1,tryitSteps.length-1);store.set('tryitStepIdx',tryitStepIdx);renderTryitStep()});
  $('#tryitDone')&&($('#tryitDone').onclick=()=>{$('#tryitFlow').innerHTML='<p>💗 Thank you for sharing a little about yourself. You can come back any time to add more, or tap Surprise Me below.</p><button class="secondary" id="tryitRestart">Go through the questions again</button>';$('#tryitRestart').onclick=()=>{tryitStepIdx=0;store.set('tryitStepIdx',0);renderTryitStep()}});
}
renderTryitStep();

/* Simple rule-based recommendation engine — no AI needed, easy to extend later. */
const suggestionCatalog=[
 {id:'coffee',text:'☕ Make your favorite drink and sit with it for a few minutes.',mood:['Sad','Tired','Stressed','Overwhelmed'],energy:['Low'],time:['10 minutes','30 minutes'],location:['Home'],fav:['Coffee','Milk tea']},
 {id:'movie',text:'🎬 Watch a comfort movie.',mood:['Sad','Tired','Bored'],energy:['Low'],time:['1 hour','Several hours'],location:['Home'],fav:['Watch movies']},
 {id:'music',text:'🎧 Listen to your favorite playlist.',mood:['Sad','Stressed','Overwhelmed'],energy:['Low','Medium'],time:['10 minutes','30 minutes'],fav:['Listen to music']},
 {id:'rainbow',text:'🌈 Build a Rainbow',mood:['Sad','Bored','Overwhelmed'],energy:['Low','Medium'],time:['10 minutes'],game:'rainbow'},
 {id:'bottles',text:'🧴 Fill the Bottles',mood:['Overwhelmed','Stressed'],energy:['Low'],time:['10 minutes','30 minutes'],game:'bottles'},
 {id:'strawberry',text:'🍓 Add Seeds to the Strawberries',mood:['Bored','Calm'],energy:['Low','Medium'],game:'strawberry'},
 {id:'diff',text:'🔎 Find the Difference',mood:['Bored','Okay'],energy:['Medium'],game:'diff'},
 {id:'fruit',text:'🍎 Grow Your Fruit',mood:['Okay','Calm'],game:'fruit'},
 {id:'trash',text:'🗑️ Things I Want to Leave Behind',mood:['Overwhelmed','Stressed'],game:'trash'},
 {id:'fire',text:'🔥 Let It Go',mood:['Sad','Stressed','Overwhelmed'],game:'fire'},
 {id:'outside',text:'🌿 Step outside for a little fresh air.',mood:['Bored','Overwhelmed'],energy:['Medium','High'],location:['Outside'],fav:['Go outside']},
 {id:'draw',text:'✏️ Draw Your Reset',mood:['Sad'],fav:['Draw'],modal:'draw'},
 {id:'journal',text:'📝 Write a little in your journal.',mood:['Overwhelmed','Sad','Stressed'],page:'journal'},
 {id:'book',text:'📖 Open your Calm Book.',mood:['Sad'],page:'book'},
 {id:'friend',text:'💗 Message a friend just to say hi.',mood:['Sad'],fav:['Hang out with friends']}
];
function scoreSuggestion(s){let score=0;if(checkin.mood&&s.mood?.includes(checkin.mood))score+=5;if(checkin.energy&&s.energy?.includes(checkin.energy))score+=4;if(checkin.time&&s.time?.includes(checkin.time))score+=4;if(checkin.location&&s.location?.includes(checkin.location))score+=4;let favs=[...(tryitProfile.freeTime||[]),...(tryitProfile.food||[]),...(tryitProfile.place||[]),...happyList];if(s.fav?.some(f=>favs.includes(f)))score+=5;if(recentSuggestions.includes(s.id))score-=3;if(completedSuggestions.includes(s.id))score-=2;return score}
function renderSuggestion(pick){
  $('#surpriseResult').innerHTML=`<p><b>${pick.text}</b></p><div class="tryit-nav"><button class="primary" id="trySugTry">Try it</button><button class="secondary" id="trySugSave">Save it</button><button class="text-btn" id="trySugAgain">Pick again</button></div>`;
  $('#trySugTry').onclick=()=>{completedSuggestions.push(pick.id);store.set('completedSuggestions',completedSuggestions);if(pick.game)openGame(pick.game);else if(pick.modal)openModal(pick.modal);else if(pick.page)go(pick.page)};
  $('#trySugSave').onclick=()=>{savedIdeas.push({text:pick.text,id:pick.id,status:'saved',created:Date.now()});store.set('savedIdeas',savedIdeas);$('#surpriseResult').insertAdjacentHTML('beforeend','<p class="saved-flash">💾 Saved to your ideas.</p>')};
  $('#trySugAgain').onclick=surpriseMe;
}
function surpriseMe(){let scored=suggestionCatalog.map(s=>({s,score:scoreSuggestion(s)})).sort((a,b)=>b.score-a.score),top=scored.slice(0,4),pick=top[Math.floor(Math.random()*top.length)].s;recentSuggestions.push(pick.id);if(recentSuggestions.length>5)recentSuggestions.shift();store.set('recentSuggestions',recentSuggestions);renderSuggestion(pick)}
$('#surpriseBtn').onclick=surpriseMe;

/* Direct activity picker on the Maybe Try This? page */
const tryitActivityList=[['rainbow','🌈 Build a Rainbow'],['diff','🔎 Find the Difference'],['strawberry','🍓 Add Seeds to Strawberries'],['bottles','🧴 Fill the Bottles'],['fruit','🍎 Grow Your Fruit'],['trash','🗑️ Leave It Behind'],['fire','🔥 Let It Go']];
$('#tryitActivities').innerHTML=tryitActivityList.map(([id,label])=>`<button data-act="${id}">${label}</button>`).join('');
$$('#tryitActivities button').forEach(b=>b.onclick=()=>openGame(b.dataset.act));

/* Favorites, Happy List, Things I Want to Try, and Saved Ideas — reuse the existing modal system. */
modalViews.favorites=function(){
  let cats=['Food','Drinks','Movies','Series','Songs','Artists','Games','Hobbies','Activities','Places','Other'],items=store.get('favorites',[]),filterCat='All',search='';
  function render(){
    let filtered=items.filter(it=>(filterCat==='All'||it.category===filterCat)&&(!search||it.name.toLowerCase().includes(search.toLowerCase())));
    content.innerHTML=`<h2>⭐ My Favorites</h2><p>Keep track of the little things you love.</p><div class="tryit-addrow"><input id="favName" maxlength="60" placeholder="Add a favorite…"><select id="favCat">${cats.map(c=>`<option>${c}</option>`).join('')}</select><button class="primary" id="favAdd">+ Add</button></div><div class="list-manager"><select id="favFilter"><option>All</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><input id="favSearch" placeholder="Search…" value="${escapeHTML(search)}">${filtered.length?filtered.map(it=>{let i=items.indexOf(it);return `<div class="lm-row"><span>${it.category!=='Other'?escapeHTML(it.category)+' · ':''}${escapeHTML(it.name)}</span><span class="lm-actions"><button data-del="${i}">🗑</button></span></div>`}).join(''):'<p><small>No favorites yet.</small></p>'}</div>`;
    $('#favFilter').value=filterCat;
    $('#favAdd').onclick=()=>{let n=$('#favName').value.trim();if(!n)return;items.push({category:$('#favCat').value,name:n});store.set('favorites',items);render()};
    $('#favFilter').onchange=()=>{filterCat=$('#favFilter').value;render()};
    $('#favSearch').oninput=()=>{search=$('#favSearch').value;render()};
    $$('[data-del]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.del,1);store.set('favorites',items);render()});
  }
  render();
};
modalViews.happylist=function(){
  content.innerHTML='';
  function render(){content.innerHTML=`<h2>💕 My Happy List</h2><p>Little things that make you happy.</p><div class="tryit-addrow"><input id="hlInput" maxlength="60" placeholder="Coffee, rain, a good song…"><button class="primary" id="hlAdd">+ Add</button></div><div class="list-manager">${happyList.length?happyList.map((v,i)=>`<div class="lm-row"><span>${escapeHTML(v)}</span><span class="lm-actions"><button data-del="${i}">🗑</button></span></div>`).join(''):'<p><small>Nothing here yet.</small></p>'}</div>`;$('#hlAdd').onclick=()=>{let v=$('#hlInput').value.trim();if(!v)return;happyList.push(v);store.set('happyList',happyList);render()};$$('[data-del]').forEach(b=>b.onclick=()=>{happyList.splice(+b.dataset.del,1);store.set('happyList',happyList);render()})}
  render();
};
modalViews.wanttotry=function(){
  function render(){content.innerHTML=`<h2>🌱 Things I Want to Try</h2><p>Little experiences to look forward to.</p><div class="tryit-addrow"><input id="wtInput" maxlength="60" placeholder="Visit Baguio, try pottery…"><button class="primary" id="wtAdd">+ Add</button></div><div class="list-manager">${wantToTry.length?wantToTry.map((it,i)=>`<div class="lm-row ${it.completed?'done':''}"><span>${escapeHTML(it.item)}</span><span class="lm-actions"><button data-done="${i}">${it.completed?'↺':'✓'}</button><button data-del="${i}">🗑</button></span></div>`).join(''):'<p><small>Nothing here yet.</small></p>'}</div>`;$('#wtAdd').onclick=()=>{let v=$('#wtInput').value.trim();if(!v)return;wantToTry.push({item:v,completed:false,created:Date.now()});store.set('wantToTry',wantToTry);render()};$$('[data-done]').forEach(b=>b.onclick=()=>{let i=+b.dataset.done;wantToTry[i].completed=!wantToTry[i].completed;if(wantToTry[i].completed)wantToTry[i].completedDate=Date.now();store.set('wantToTry',wantToTry);render()});$$('[data-del]').forEach(b=>b.onclick=()=>{wantToTry.splice(+b.dataset.del,1);store.set('wantToTry',wantToTry);render()})}
  render();
};
modalViews.savedideas=function(){
  function render(){content.innerHTML=`<h2>💾 Saved Ideas</h2><p>Little suggestions you've saved for later.</p><div class="list-manager">${savedIdeas.length?savedIdeas.map((it,i)=>`<div class="lm-row ${it.status==='completed'?'done':''}"><span>${escapeHTML(it.text)}</span><span class="lm-actions"><button data-try="${i}">Try</button><button data-complete="${i}">✓</button><button data-del="${i}">🗑</button></span></div>`).join(''):'<p><small>Nothing saved yet — try Surprise Me and tap Save it.</small></p>'}</div>`;
    $$('[data-try]').forEach(b=>b.onclick=()=>{let it=savedIdeas[+b.dataset.try],match=suggestionCatalog.find(s=>s.id===it.id);closeModal();if(match?.game)openGame(match.game);else if(match?.modal)openModal(match.modal);else if(match?.page)go(match.page)});
    $$('[data-complete]').forEach(b=>b.onclick=()=>{savedIdeas[+b.dataset.complete].status='completed';store.set('savedIdeas',savedIdeas);render()});
    $$('[data-del]').forEach(b=>b.onclick=()=>{savedIdeas.splice(+b.dataset.del,1);store.set('savedIdeas',savedIdeas);render()});
  }
  render();
};

go(location.hash.slice(1)||'home');
